Repository operator-framework/operator-lib, pull requests merged in 2021-07, with the labels that each got.

#61 Update condition lib to use v2
  conditions/conditions.go
  conditions/conditions_test.go
  go.sum
Labels: approved, lgtm

#65 Depreciate ErrNoOperatorCondition
  conditions/conditions.go
  conditions/conditions_test.go
Labels: approved, lgtm

#66 Remove ErrNoOperatorCondition error
  conditions/conditions.go
Labels: approved, lgtm

#60 handler,predicate: pause object reconciliation by annotation
  go.mod
  handler/example_test.go
  handler/instrumented_enqueue_object_test.go
  handler/pause.go
  internal/annotation/filter.go
  internal/annotation/filter_test.go
  internal/annotation/suite_test.go
  predicate/example_test.go
  predicate/pause.go
Labels: approved, kind/feature, lgtm

#70 Fix permission issue when settin the operator-condition
  conditions/conditions.go
Labels: approved, lgtm, ok-to-test
